# Changes here will be overwritten by Copier
_commit: a283751
_src_path: https://github.com/browniebroke/pypackage-template
add_me_as_contributor: false
cli_name: aiortm
copyright_year: '2025'
documentation: false
email: marhje52@gmail.com
full_name: Martin Hjelmare
github_username: MartinHjelmare
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: Apache Software License 2.0
package_name: aiortm
project_name: aiortm
project_short_description: Use the Remember the Milk API with aiohttp.
project_slug: aiortm
run_uv_sync: false
setup_github: false
setup_pre_commit: true

