name: CI

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  psr-ci:
    uses: MartinHjelmare/github-actions-workflows/.github/workflows/psr-ci.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
